backend/src/main/java/com/alibaba/higress/console/WebMvcInitializer.java
When accessing a path with neither an API controller nor any actual static resource file bound to it, fallback to index.html so frontend routing can work properly here.
=> Fallback to the homepage resource when the target resource is not found.

frontend/ice.config.mts, frontend/src/pages/404.tsx
The original usage of generic route for handling 404 errors will cause a "*.html" file being generated by the build process. And Windows platform doesn't support any file name containing a "*" character, but Linux does.
This PR replaces the implicit wildcard route definition using file name with an explicit route definition in the ice.config.mts file. Problem solved.
=> Fix the failure when building frontend project in Windows platform caused used by the "*.html" file generated by the generic route.

backend/pom.xml, backend/src/main/java/com/alibaba/higress/console/aop/ApiStandardizationAspect.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
Fix bugs in TLS certificate management function
1. Unable to delete certificates.
2. Delete APIs return 200 status instead of 204.
3. No error log when failed to parse certificate data
=> Fix bugs in TLS certificate management function

helm/templates/deployment.yaml
Set the name of admin secret in the deployment so the console can work when it is installed with a name other than "higress-console".
=> fix: Set the name of admin secret in the deployment

backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSource.java, frontend/src/pages/service-source/components/SourceForm/index.tsx
Mark zkServicesPath property of ServiceSource as optional
=> fix: Mark zkServicesPath property of ServiceSource as optional

frontend/src/pages/service/index.tsx
Fix the incorrect filter result in service source page.
Before:
After:
=> fix: Fix the incorrect filter result in service source page

backend/src/main/java/com/alibaba/higress/console/service/WasmPluginInstanceServiceImpl.java
feat: Return an empty Wasm plugin instance if not configured
=> feat: Return an empty Wasm plugin instance if not configured

backend/src/main/java/com/alibaba/higress/console/service/WasmPluginServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java, backend/src/main/resources/plugins/basic-auth/spec.yaml, backend/src/main/resources/plugins/bot-detect/spec.yaml, backend/src/main/resources/plugins/key-auth/spec.yaml
1. Set the scope of global_auth property to GLOBAL
2. Fix the incorrect example configuration of bot-detect plugin
3. Keep the current plugin instances after a custom plugin being upgraded
4. Fix the incorrect rawConfigurations value of jwt-auth plugin
5. Return an empty object or string when querying config schema or readme file of a custom plugin
6. Make sure the new custom Wasm plugin is globally disabled by default
=> fix: Fix some bugs in Wasm plugin management module

frontend/src/pages/plugin/components/Cors/index.tsx, frontend/src/pages/plugin/components/Retries/index.tsx, frontend/src/pages/plugin/components/Rewrite/index.tsx
Unify the UI style of strategy configuration drawers.
Before:
After:
=> feat: Unify the UI style of strategy configuration drawers

helm/templates/NOTES.txt
Only ask user to access Higress Console through Ingress, since accessing the pod of console directly won't return 404 when trying to access the build-in Grafana dashboard.
=> fix: Only ask user to access Higress Console through Ingress

backend/src/main/java/com/alibaba/higress/console/constant/CommonKey.java, backend/src/main/java/com/alibaba/higress/console/service/DashboardServiceImpl.java
Support overwriting the existed built-in dashboard configuration during startup. Overwriting is enabled by default. And user can disable it by setting the environment variable  `HIGRESS_CONSOLE_DASHBOARD_OVERWRITE_WHEN_STARTUP` to `false`.
=> feat: Support overwriting the existed built-in dashboard configuration during startup

helm/templates/grafana.yaml, helm/templates/prometheus.yaml
Use the current storageClass for existed PVCs when upgrading to fix the malfunction of upgrading Higress Console with `helm upgrade`.
=> fix: Use the current storageClass for existed PVCs when upgrading

backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
Compensate WasmPlugin.phase field with the default value if it's not set in the CR
=> fix: Compensate WasmPlugin.phase field if not set in the CR

backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/WasmPluginInstanceServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/WasmPluginServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java
Unify the name prefix of CRUD methods used in KubernetesClientService:
- list
- read
- create
- replace
- delete
=> fix: Unify the name prefix of CRUD methods used in KubernetesClientService

backend/src/main/java/com/alibaba/higress/console/service/DashboardServiceImpl.java
Fix startup error thrown when built-in o11y suite is not installed. Only parse the Grafana API URL when built-in o11y suite is installed.
=> fix: Fix startup error thrown when built-in o11y suite is not installed

backend/src/main/java/com/alibaba/higress/console/service/SessionServiceImpl.java
Use a non-printable character instead of comma to as the separator when building auth tokens, so password containing comma won't break the parse logic.
=> fix: Fix the auth failure when the password contains any comma

backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/Route.java, backend/src/main/java/com/alibaba/higress/console/service/RouteServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java, frontend/src/interfaces/route.ts, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/route/components/FactorGroup/index.tsx, frontend/src/pages/route/components/KeyValueGroup/index.module.css, frontend/src/pages/route/components/KeyValueGroup/index.tsx, frontend/src/pages/route/components/RouteForm/index.tsx, frontend/src/pages/route/index.tsx
Support configuring custom annotations in the route editing form.
**Note:**
If user configures a console-supported feature (e.g. CORS) with Nginx Ingress annotations (with prefix `nginx.ingress.kubernetes.io/`), it won't be changed to Higress annotation (with prefix `higress.io/`) automatically.
User is still able to open the edit dialog of that route, but can't save it, because the API will return an error when trying to save an Nginx Ingress annotation with its corresponding Higress key supported by Console.
fixes #271
=> feat: Support configuring custom annotations

backend/src/main/java/com/alibaba/higress/console/WebMvcInitializer.java
Use "Last-Modified" to controller the static resource caching mechanism, so index.html won't be cached too long.
=> fix: Use "Last-Modified" to controller the static resource caching mechanism

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/RouteServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ServiceSourceServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/WasmPluginInstanceServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesClientService.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java
Return null when trying to load a non-existent K8s resource, so we don't need to check the response status of ApiException everywhere.
=> feat: Return null when trying to load a non-existent K8s resource

backend/console/src/main/java/com/alibaba/higress/console/service/ConfigServiceImpl.java
Support starting up without the ConfigMap with system configs, so we don't need to create it during installation.
This shall only be merged after #281
=> feat: Support starting up without the ConfigMap with system configs

backend/console/src/main/java/com/alibaba/higress/console/service/SystemServiceImpl.java
Suppress the exception log when git.properties doesn't exist.
=> feat: Suppress the exception log when git.properties doesn't exist

helm/templates/prometheus.yaml, helm/values.yaml
…alibaba/higress/issues/727 fix #289
fix https://github.com/alibaba/higress/issues/727
fix #289
=> feat: add securityContext for o11y.prometheus

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/service-source/components/SourceForm/index.tsx
Add a special note to the port field of Nacos 2.0 service source, letting user know he/she needs to keep an additional port accessiable as well.
=> fix: Add a special note to the port field of Nacos 2.0 service source

backend/console/src/main/java/com/alibaba/higress/console/constant/SystemConfigKey.java, backend/console/src/main/java/com/alibaba/higress/console/constant/UserConfigKey.java, backend/console/src/main/java/com/alibaba/higress/console/controller/AiProxyController.java
Add a controller to forward requests to the specified AI service.
Related environment variables:
- HIGRESS_CONSOLE_AI_PROXY_SERVICE_URL
- HIGRESS_CONSOLE_AI_PROXY_SERVICE_TOKEN
If configured as following:
```bash
HIGRESS_CONSOLE_AI_PROXY_SERVICE_URL=https://api.openai.com/
HIGRESS_CONSOLE_AI_PROXY_SERVICE_TOKEN=sk-higress-demo
```
requests sent to `http://demo.higress.io/aiproxy/v1/chat/completion` will be forwarded to `https://api.openai.com/v1/chat/completion` with HTTP header `Authorization: Bearer sk-higress-demo`.
=> feat: Add a controller to forward requests to the specified AI service

frontend/src/services/request.tsx
Add the current timestamp into the query string of GET requests so the browser won't load the cached responses.
=> feat: Avoid loading cached GET responses on the frontend

backend/console/src/main/java/com/alibaba/higress/console/constant/SystemConfigKey.java, backend/console/src/main/java/com/alibaba/higress/console/controller/AiProxyController.java, backend/console/src/main/java/com/alibaba/higress/console/service/SessionServiceImpl.java, helm/templates/deployment.yaml
Support loading LLM service info from a K8s Secret.
The default secret name is higress-console. Corresponding key names are:
- aiProxyServiceUrl
- aiProxyServiceToken
Configurations are reloaded every minute.
=> feat: Support loading LLM service info from a K8s Secret

backend/sdk/src/test/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverterTest.java
This PR is mainly to increase the unit test coverage of `KubernetesModelConverter`
此 PR 主要是为了增加 `KubernetesModelConverter` 的单元测试覆盖率
fix #97
Not applicable
不适用该选项
- All unit test functions are considered passed if they pass
所有单元测试函数如果通过，则视为通过
- The newly added unit tests now provide full coverage for all public functions.
新添加的单元测试，已经覆盖所有的`public`函数
- Detailed unit test coverage changes are shown in the following table
详细的单元测试覆盖率变化如下表所示
| |Amount| class,% |Method,% |Line,% |Branch,% |
| ---- | ---- | ---- | ---- | ---- | ---- |
| Original data |26| 50% (1/2)|47% (34/72)|32% (291/893)|24% (142/569)
| After addition |92| 100% (2/2)|90% (65/72)|76% (684/893)|57% (328/569)
=> feat:add unit test for KubernetesModelConverter

backend/sdk/src/main/resources/plugins/traffic-tag/spec.yaml
Fix the informal title and icon of traffic-tag plugin.
=> fix: Fix the informal title and icon of traffic-tag plugin

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java
Without this fix, submitting a route with following configurations would result a 500 error returned by the API:
=> fix: Fix the 500 error when submitting a route with a blank query or header match condition

helm/templates/NOTES.txt
=> fix: Only show ingress related notes when ingress is enabled

backend/console/src/main/java/com/alibaba/higress/console/controller/ConsumersController.java, backend/console/src/main/java/com/alibaba/higress/console/controller/ai/LlmProvidersController.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ai/AiRouteAuthConfig.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ai/AiRouteFallbackConfig.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ai/AiRouteFallbackStrategy.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ai/LlmProvider.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/consumer/Credential.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/consumer/KeyAuthCredential.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/HigressServiceProviderImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AbstractLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AiRouteServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/consumer/ConsumerService.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/consumer/ConsumerServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/consumer/CredentialHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/consumer/KeyAuthCredentialHandler.java, backend/sdk/src/test/java/com/alibaba/higress/sdk/service/consumer/KeyAuthCredentialHandlerTest.java
1. Update the data models of Consumer, LlmProvider and AiRoute.
2. Return the original tokens instead of masked ones in ConsumersController and LlmProviderController.
3. Fix auth functions in AI route.
=> feat: Update AI console function.

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/crd/wasm/FailStrategy.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/crd/wasm/V1alpha1WasmPluginSpec.java
When user creates a new Wasm plugin config or updates an existed Wasm plugin config in the console, the `failStrategy` field in the generated WasmPlugin resource will be set to `FAILED_OPEN`.
=> fix: Use failStrategy FAILED_OPEN in all generated WasmPlugin resources

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java, backend/sdk/src/test/java/com/alibaba/higress/sdk/service/WasmPluginInstanceServiceTest.java
Set the defaultConfigDisable of WasmPlugin CR to false by default, so it won't break the WasmPlugin config pushing if user only configures plugin in route or domain level.
fixes https://github.com/alibaba/higress/issues/1517
=> fix: Set the defaultConfigDisable of WasmPlugin CR to false by default

frontend/src/interfaces/service-source.ts, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/service-source/components/SourceForm/index.tsx, frontend/src/pages/service-source/index.tsx
```yaml
apiVersion: networking.higress.io/v1
kind: McpBridge
metadata:
creationTimestamp: "2024-12-05T09:38:55Z"
generation: 19
name: default
namespace: higress-system
resourceVersion: "2054673"
uid: f73e338c-3dc6-477e-9307-1eabe49a3ca8
spec:
registries:
- domain: 1.1.1.1
nacosGroups:
- DEFAULT_GROUP
nacosNamespaceId: ""
name: nacos
port: 1233
type: nacos2
- domain: "123123"
nacosGroups:
- DEFAULT_GROUP
nacosNamespaceId: ""
name: nacosv2
port: 12312
type: nacos
- domain: 1.1.1.1
name: zk
port: 123
type: zookeeper
zkServicesPath: []
- domain: 123.1.1.1:1234
name: test
port: 80
protocol: https
sni: http
type: static
- domain: www.test.com
name: dns
port: 123
protocol: grpcs
sni: testt
type: dns
- domain: 123.1.1.1
name: testev
port: 1234
type: eureka
- domain: 10.1.2.3:50005
name: local …
```
=> feat: Support configuring protocol and SNI for service sources with static or dns type

backend/console/pom.xml, backend/console/src/main/java/com/alibaba/higress/console/config/SwaggerConfig.java, backend/pom.xml, backend/sdk/pom.xml
Re-integrate Swagger with SpringDoc, since the SpringFox project is not alive any more.
http://localhost:8001/swagger-ui/index.html
http://localhost:8001/v3/api-docs/Higress
fixes #378
=> feat: Re-integrate Swagger with SpringDoc

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesClientService.java
Allow connecting to a separate K8s server when running in a K8s cluster, so we can run all-in-one image in a K8s cluster.
=> feat: Allow connecting to a separate K8s server when running in a K8s cluster

backend/console/src/main/resources/application.properties
Enable gzip for responses larger than 2 KiB to improve user experience.
=> feat: Enable gzip for responses larger than 2 KiB

backend/console/pom.xml, backend/console/src/main/java/com/alibaba/higress/console/controller/SystemController.java, backend/console/src/main/java/com/alibaba/higress/console/service/DashboardService.java, backend/console/src/main/java/com/alibaba/higress/console/service/DashboardServiceImpl.java, backend/pom.xml
Use a better way to determine whether we have a built-in dashboard, so grafana won't block the start-up of console.
=> fix: Use a better way to determine whether we have a built-in dashboard

backend/sdk/src/main/java/com/alibaba/higress/sdk/constant/plugin/config/AiStatisticsConfig.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AiRouteServiceImpl.java
Enable ai-statistics plugin for AI routes by default.
```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
annotations:
higress.io/wasm-plugin-description: Provides statistics of token usage, including
logs, monitoring, and alerts.
higress.io/wasm-plugin-icon: https://img.alicdn.com/imgextra/i1/O1CN018iKKih1iVx287RltL_!!6000000004419-2-tps-42-42.png
higress.io/wasm-plugin-title: AI Statistics
creationTimestamp: "2025-01-14T04:18:57Z"
generation: 2
labels:
higress.io/resource-definer: higress
higress.io/wasm-plugin-built-in: "true"
higress.io/wasm-plugin-category: ai
higress.io/wasm-plugin-name: ai-statistics
higress.io/wasm-plugin-version: 1.0.0
name: ai-statistics-1.0.0
namespace: higress-system
resourceVersion: "2945137"
uid: bde30c13-b17d-4611-977a-ad52b0e228bd …
```
=> feat: Enable ai-statistics plugin for AI routes by default

frontend/src/interfaces/llm-provider.ts, frontend/src/pages/ai/components/RouteForm/index.tsx
Fix the bug that the fallback model of an AI Route cannot be saved.
fixes https://github.com/higress-group/higress-console/issues/415
=> fix: Fix a bug in saving the fallback model of an AI Route

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/route/index.tsx
add search filter for routes in the route management page.
A service associated with a route belongs to multiple namespaces. Is it necessary to display namespaces and filter by namespace as described in the https://github.com/alibaba/higress/issues/1659? I can try to continue adding this functionality in this PR.
fix: https://github.com/alibaba/higress/issues/1659
=> feat: add search filter for routes in the route management page

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AiRouteServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/crd/wasm/MatchRule.java
Delete AI route fallback configurations, including EnvoyFilter, WasmPlugin configurations, Ingresses, when disabling fallback feature or deleting an AI route with fallback enabled.
=> fix: Make sure AI route fallback resources can be deleted correctly

frontend/src/pages/ai/components/ProviderForm/index.tsx
Allow user to input any URL as a custom OpenAI endpoint.
=> fix: Allow user to input any URL as a custom OpenAI endpoint

backend/sdk/src/main/resources/plugins/basic-auth/spec.yaml
Add a sample to the title field of credential field in basic auth plugin, so user can know how to set the value.
=> fix: Update the title of credential field in basic auth plugin

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AbstractLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AzureLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/LlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/LlmProviderServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/OllamaLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/OpenaiLlmProviderHandler.java
Previously, the ollamaServerPort in the configuration map is a string, causing `serverPortObj instanceof Integer serverPort` check fails, resulting a DEFAULT_PORT of 11434 used in the generated McpBridge registry.
Here we rename the `validationConfig` method to `normalizeConfig`, giving it more responsibility to fix value types and generate additional configurations besides the original validation responsibility.
=> fix: Fix the incorrect upstream  port value used when the ollama instance uses a custom port

backend/console/src/main/java/com/alibaba/higress/console/aop/ApiStandardizationAspect.java, backend/console/src/main/resources/application.properties
The K8s ApiException itself usually doesn't contain any message, resulting an empty info logged. Adding some response details would help the issue diagnostics. And an extra trace ID is added to co-relate these two log entries.
=> chore: Add K8s API response details when logging a K8s ApiException

backend/console/src/main/java/com/alibaba/higress/console/controller/WasmPluginsController.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/WasmPlugin.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/WasmPluginService.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/WasmPluginServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/ImageUrl.java, backend/sdk/src/test/java/com/alibaba/higress/sdk/service/WasmPluginServiceTest.java, backend/sdk/src/test/java/com/alibaba/higress/sdk/service/kubernetes/ImageUrlTest.java, frontend/src/pages/plugin/components/Wasm/index.tsx
Support customizing image URL of built-in plugins with two ways:
1. Global customization
- User can add an env variable `HIGRESS_ADMIN_WASM_PLUGIN_CUSTOM_IMAGE_URL_PATTERN` or Java property `higress-admin.wasmplugin.custom-image-url-pattern` when starting the console. The value can contain two placeholders, `${name}` and `${version}`, which will be replaced with actual plugin metadata field values.
2. Specified customization
- User can edit built-in plugins on the console webpage and change the image URL.
- ![image](https://github.com/user-attachments/assets/4b5b94f5-7197-4e85-b099-4662a7182188)
=> feat: Support customizing image URL of built-in plugins

helm/templates/deployment.yaml
Remove two redundant envs, which are already defined in the base image:
- JAVA_HOME
- LANG
=> fix: Remove two redundant envs

backend/sdk/src/main/java/com/alibaba/higress/sdk/constant/plugin/config/KeyAuthConfig.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/consumer/KeyAuthCredential.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/consumer/ConsumerServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/consumer/KeyAuthCredentialHandler.java, backend/sdk/src/test/java/com/alibaba/higress/sdk/service/consumer/KeyAuthCredentialHandlerTest.java, frontend/src/pages/consumer/components/ConsumerForm/index.tsx, frontend/src/pages/consumer/index.tsx
Support configuring multiple key-auth credentials in one consumer.
Support reading existed configurations with "credential" key, but only write configs to the new "credentials" key.
=> feat: Support configuring multiple key-auth credentials in one consumer

backend/sdk/src/main/resources/templates/envoyfilter-route-fallback.yaml
The file src/main/resources/templates/envoyfilter-route-fallback.yaml hardcodes the namespace as higress-system. When Higress is started in a different namespace, configuring the AI route fallback will cause some strange issues.
When creating the EnvoyFilter resource using the Kubernetes client, we pass in the namespace parameter. The expected behavior is to use this parameter directly, rather than hardcoding it as higress-system.
Error log
```
2025-04-16 16:17:01.639 ERROR 70396 --- [nio-8080-exec-2] c.a.h.c.aop.ApiStandardizationAspect     {traceId=1e061189-dd27-4b6d-beaa-0eea648e328e} : Related K8s API response: Code=400 Body={"kind":"Status","apiVersion":"v1","metadata":null,"status":"Failure","message":"the namespace of the provided object does not match the namespace sent on the …
```
=> fix: Fix namespace in envoyfilter-route-fallback.yaml template

backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ai/LlmProviderType.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/BedrockLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/LlmProviderServiceImpl.java, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/ai/components/ProviderForm/index.tsx, frontend/src/pages/ai/components/RouteForm/index.tsx, frontend/src/pages/ai/configs.tsx, frontend/src/pages/ai/provider.tsx
1. Support a new LLM provider type, AWS Bedrock.
2. Allow showing the default endpoint of each LLM provider in the list.
3. Change the default endpoint of Qwen since the compatibility mode isn't enabled by default.
=> feat: Support a new LLM provider type, AWS Bedrock

.github/workflows/deploy-to-oss.yaml, backend/console/pom.xml
Fix the OpenAPI doc generation job.
1. Install the full higress instead of higress-console, since the initialization of higress console requires WasmPlugin CRD.
2. Enable SpringDoc when executing the OpenAPI doc generation plugin, because we have it disabled by default now.
=> fix: Fix the OpenAPI doc generation job

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/ai/components/ProviderForm/index.tsx
Add a modal telling user how to refer to token values in Secrets.
fixes https://github.com/alibaba/higress/issues/2140
=> feat: Add a modal telling user how to refer to token values in Secrets

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/service-source/components/SourceForm/index.tsx
Only show domains with route in the MCP domain list for Nacos 3.x.
fixes https://github.com/alibaba/higress/issues/2174
=> fix: Only show domains with route in the MCP domain list for Nacos 3.x

backend/console/src/main/java/com/alibaba/higress/console/config/SdkConfig.java, backend/console/src/main/java/com/alibaba/higress/console/constant/SystemConfigKey.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/config/HigressServiceConfig.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/constant/HigressConstants.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/Service.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/HigressServiceProviderImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ServiceServiceByApiServerImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesClientService.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java, helm/templates/deployment.yaml
在 higressConfig 中增加一个参数：dependControllerApi，用于支持调整对于 组件 higress controller的依赖。默认行为保持原来的依赖关系，允许在不使用注册中心时，将其依赖关系解耦。使得它只依赖 k8s apiserver
fixes #505
=> If service discovery from the registry is not used, the architecture allows decoupling from the Higress Controller.

backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ai/LlmProviderEndpoint.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AbstractLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AzureLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/BedrockLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/DefaultLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/LlmProviderServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/OllamaLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/OpenaiLlmProviderHandler.java, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/ai/components/ProviderForm/index.tsx, frontend/src/pages/ai/configs.tsx, frontend/src/pages/ai/provider.tsx
1. Support configuring multiple endpoints for custom OpenAI LLM providers.
1. Only URLs with IP+Port are supported when configuring multiple endpoints.
2. All the URLs must have the same protocol and path.
3. Refactor LlmProvider endpoint management logic.
=> feat: Support configuring multiple endpoints for custom OpenAI LLM providers

helm/templates/deployment.yaml, helm/values.yaml
Plugin server supports k8s one-click deployment and configures the default download URL of the plugin
fixes [#2232](https://github.com/alibaba/higress/issues/2232), [#2280](https://github.com/alibaba/higress/issues/2280),[#2312](https://github.com/alibaba/higress/issues/2312)
=> feat: Plugin server supports k8s deployment and configures the default download URL of the plugin

helm/values.yaml
Changing the default PVC access mode to `ReadWriteOnce`, which is more commonly used and sufficient for default setups. Prometheus and Grafana run with a single replica by default, so `ReadWriteMany` is unnecessary in most cases. Users who need multiple replicas can switch to `ReadWriteMany` if required.
fixes: https://github.com/alibaba/higress/issues/204
Related PR: https://github.com/higress-group/higress-group.github.io/pull/437
=> change rwxSupported's default value to false

backend/sdk/src/test/java/com/alibaba/higress/sdk/service/WasmPluginImageChecker.java
Add a UT case to check whether Wasm plugin images are up-to-date by comparing the manifest of the current used image tag and the latest tag.
Require docker to execute.
=> feat: Add a UT case to check whether Wasm plugin images are up-to-date

frontend/src/pages/mcp/components/EditToolDrawer.tsx, frontend/src/pages/mcp/components/McpServerCommand.tsx, frontend/src/pages/mcp/detail.tsx
- 在 EditToolDrawer、McpServerCommand 和 MCPDetail 组件中，更新 MonacoEditor 的引入方式
- 配置 Monaco 编辑器的按需加载，提高性能
fixes #569
=> refactor(mcp): 优化 Monaco 编辑器的加载方式

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/WasmPluginInstanceServiceImpl.java
The override used before was `listWasmPlugin(String name, String version, Boolean builtIn)`, which doesn't match the scenario, causing non-internal instances being returned here. This PR fixes this problem.
fixes https://github.com/alibaba/higress/issues/2736
=> fix: Fix the incorrect logic of filtering V1alpha1WasmPlugin by internal flag

backend/sdk/src/main/java/com/alibaba/higress/sdk/util/ValidateUtil.java, backend/sdk/src/test/java/com/alibaba/higress/sdk/util/ValidateUtilTest.java
Use the same regex pattern to validate domain names so domains with a long top-level name, like `test.internal` can be accepted.
=> fix: Sync the domain regex pattern between backend and frontend

frontend/src/pages/mcp/components/DatabaseConfig.tsx, frontend/src/pages/mcp/components/McpFormDrawer.tsx, frontend/src/pages/mcp/constant.ts
本次更新为MCP服务器管理功能添加了对PostgreSQL和ClickHouse数据库的支持，同时修复了数据库连接字符串解析问题。
- 支持PostgreSQL数据库连接（postgres://username:password@host:port/dbname）
- 支持ClickHouse数据库连接（tcp://host:port?database=xxx&username=xxx&password=xxx）
- 优化MySQL数据库连接字符串格式
- 修复数据库连接字符串解析问题
- 统一数据库类型选项（移除SQLite，标准化命名）
- 改进DSN验证逻辑，支持多种数据库类型
- 更新`computeDSN`函数支持多种数据库格式
- 重构`McpFormDrawer`组件中的DSN解析逻辑
- 更新正则表达式常量以支持不同数据库类型
- 优化表单验证规则
Closes #561
=> feat(mcp): 支持 PostgreSQL 和 ClickHouse 数据库连接

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/consumer/ConsumerServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/consumer/KeyAuthCredentialHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java, backend/sdk/src/test/java/com/alibaba/higress/sdk/service/consumer/ConsumerServiceTest.java, backend/sdk/src/test/java/com/alibaba/higress/sdk/service/consumer/KeyAuthCredentialHandlerTest.java
Fix bugs in enabling auth with no allowed consumer.
1. Do not clear allowed consumer list when performing toggle-only operation.
2. Fix the incorrect auth status display when auth is enabled with no allowed consumer.
=> fix: Fix bugs in enabling auth with no allowed consumer

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/mcp/McpServiceContextImpl.java, backend/sdk/src/test/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverterTest.java
Exclude built-in labels when filling Route.customLabels so they can be removed during update.
fixes https://github.com/alibaba/higress/issues/2868
=> fix: Fix the incorrect logic dealing with Route.customLabels

frontend/src/pages/service-source/components/SourceForm/index.tsx
Show the fixed service port 80 for static service sources.
=> feat: Show the fixed service port 80 for static service sources
