higress-group/higress-console

frontend/package.json, frontend/src/components/Footer/index.tsx, frontend/src/interfaces/route.ts, frontend/src/interfaces/service.ts, frontend/src/pages/login/index.tsx, frontend/src/pages/route/components/FactorGroup/index.module.css, frontend/src/pages/route/components/FactorGroup/index.tsx, frontend/src/pages/route/components/RouteForm/index.tsx, frontend/src/pages/route/index.tsx, frontend/src/pages/service/index.tsx, frontend/src/services/api.d.ts, frontend/src/services/index.ts, frontend/src/services/request.tsx, frontend/src/services/route.ts, frontend/src/services/service.ts
Signed-off-by: abuexclusive <1399939413@qq.com>
=> add route fork

frontend/package-lock.json, frontend/package.json, frontend/src/app.ts, frontend/src/services/request.tsx
Signed-off-by: abuexclusive <1399939413@qq.com>
=> production env api

helm/.helmignore, helm/Chart.yaml, helm/templates/NOTES.txt, helm/templates/_helpers.tpl, helm/templates/deployment.yaml, helm/templates/ingress.yaml, helm/templates/service.yaml, helm/values.yaml
=> Add helm charts for deploying higress console.

frontend/package-lock.json, frontend/package.json, frontend/public/locales/en-US/translation.json, frontend/public/locales/zh-CN/translation.json, frontend/src/app.ts, frontend/src/components/AvatarDropdown/index.tsx, frontend/src/components/CardAreaChart/index.tsx, frontend/src/components/CardBarChart/index.tsx, frontend/src/components/CardGroupBarChart/index.tsx, frontend/src/components/CardLineChart/index.tsx, frontend/src/components/CardPieChart/index.tsx, frontend/src/components/CardRankChart/index.tsx, frontend/src/components/CardTypebarChart/index.tsx, frontend/src/components/LanguageDropdown/index.module.css, frontend/src/components/LanguageDropdown/index.tsx, frontend/src/i18n.ts, frontend/src/menuConfig.tsx, frontend/src/pages/$.tsx, frontend/src/pages/domain/components/DomainForm/index.tsx, frontend/src/pages/domain/index.tsx, frontend/src/pages/index.tsx, frontend/src/pages/layout.tsx, frontend/src/pages/login/index.tsx, frontend/src/pages/route/components/FactorGroup/index.tsx, frontend/src/pages/route/components/RouteForm/index.tsx, frontend/src/pages/route/index.tsx, frontend/src/pages/service-source/index.tsx, frontend/src/pages/service/index.tsx, frontend/src/services/exception.tsx, frontend/src/services/request.tsx
https://github.com/higress-group/higress-console/issues/16
=> Add i18n support.

frontend/src/interfaces/source.ts, frontend/src/pages/service-source/components/SourceForm/index.tsx, frontend/src/pages/service-source/index.tsx, frontend/src/services/source.ts
=>  完成服务来源页面绘制

backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java, backend/src/main/resources/application.properties, frontend/package.json
1. Support accessing istiod service outside the K8s cluster.
2. Use a better way to determine whether the console is running inside a K8s cluster or not.
3. Add build-dev command into the frontend project.
=> Improve the local development experience:

backend/pom.xml, backend/src/main/java/com/alibaba/higress/console/constant/CommonKey.java, backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java, backend/src/main/java/com/alibaba/higress/console/controller/DomainController.java, backend/src/main/java/com/alibaba/higress/console/controller/RouterController.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/Destination.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/Domain.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/Result.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/Route.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/RoutePredicates.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/RoutePredicatesTypeEnum.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/Service.java, backend/src/main/java/com/alibaba/higress/console/service/RouteServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java, backend/src/main/java/com/alibaba/higress/console/util/KubernetesUtil.java, backend/src/test/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientServiceTest.java, backend/src/test/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverterTest.java, frontend/ice.config.mts, frontend/public/locales/en-US/translation.json, frontend/public/locales/zh-CN/translation.json, frontend/src/pages/route/components/RouteForm/index.tsx, frontend/src/pages/route/index.tsx, frontend/src/services/exception.tsx, frontend/src/services/request.tsx
=> Implement basic route management function.

backend/src/main/java/com/alibaba/higress/console/controller/dto/Service.java, backend/src/main/java/com/alibaba/higress/console/service/ServiceServiceImpl.java
https://en.wikipedia.org/wiki/Communication_endpoint
=> Fix the issue that service endpoints show empty on the web page.

frontend/ice.config.mts, frontend/src/pages/index.tsx
=> Redirect to the route management page when visiting the home page

helm/values.yaml
=> update higress class

backend/src/main/java/com/alibaba/higress/console/constant/CommonKey.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java
Set ingressClassName to higress when generating V1Ingress object.
=> Set ingressClassName to higress when generating V1Ingress object.

CONTRIBUTING.md, README.md, backend/src/main/java/com/alibaba/higress/console/service/ServiceServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/dto/IstioEndpoint.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/dto/IstioEndpointShard.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/dto/Port.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/dto/RegistryzService.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/dto/RegistryzServiceAttributes.java, backend/start.sh
Update project structure and add contribution guide.
#68
=> Update project structure and add contribution guide.

backend/src/main/java/com/alibaba/higress/console/constant/CommonKey.java, backend/src/main/java/com/alibaba/higress/console/service/ServiceServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java
Exclude services in system namespaces (e.g.: kube-system) when getting service list.
#75
=> Exclude services in system namespaces when getting service list.

backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java, backend/src/main/java/com/alibaba/higress/console/controller/ServiceSourceController.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSource.java, backend/src/main/java/com/alibaba/higress/console/controller/util/ValidateUtil.java, backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceService.java, backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/mcp/V1McpBridge.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/mcp/V1McpBridgeList.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/mcp/V1McpBridgeSpec.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/mcp/V1RegistryConfig.java
create,update,list,delete mcpbridge
=> create,update,list,delete mcpbridge

backend/src/main/java/com/alibaba/higress/console/aop/ApiStandardizationAspect.java, backend/src/main/java/com/alibaba/higress/console/constant/CommonKey.java, backend/src/main/java/com/alibaba/higress/console/controller/SessionController.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/LoginRequest.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/Response.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/User.java, backend/src/main/java/com/alibaba/higress/console/controller/exception/AuthException.java, backend/src/main/java/com/alibaba/higress/console/service/SessionService.java, backend/src/main/java/com/alibaba/higress/console/service/SessionServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/SessionUserHelper.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/mcp/V1McpBridge.java, backend/src/main/java/com/alibaba/higress/console/util/AesUtil.java, frontend/public/locales/en-US/translation.json, frontend/public/locales/zh-CN/translation.json, frontend/src/app.ts, frontend/src/components/AvatarDropdown/index.tsx, frontend/src/interfaces/user.ts, frontend/src/pages/layout.tsx, frontend/src/pages/login/index.tsx, frontend/src/services/request.tsx, frontend/src/services/user.ts, helm/templates/NOTES.txt, helm/templates/_helpers.tpl, helm/templates/deployment.yaml, helm/templates/ingress.yaml, helm/templates/secret.yaml, helm/templates/service.yaml, helm/values.yaml
Add user login and API authentication support.
fixes #74
Depends on [#77](https://github.com/higress-group/higress-console/pull/77)
=> Add user login and API authentication support

.github/workflows/deploy-to-oss.yaml
Support deploying helm charts to Aliyun OSS when creating a new tag with name beginning with "v".
#89
=> Support deploying helm charts to Aliyun OSS when creating a new tag

backend/src/main/java/com/alibaba/higress/console/client/grafana/GrafanaClient.java, backend/src/main/java/com/alibaba/higress/console/client/grafana/models/GrafanaDashboard.java, backend/src/main/java/com/alibaba/higress/console/controller/DashboardController.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/DashboardInfo.java, backend/src/main/java/com/alibaba/higress/console/service/DashboardService.java, backend/src/main/java/com/alibaba/higress/console/service/DashboardServiceImpl.java, backend/src/main/resources/dashboard/main.json, helm/templates/prometheus.yaml
1. Support re-initializing Grafana dashboard with the built-in configuration.
2. Update built-in dashboard configuration to fix some table display issues.
3. Support collecting container CPU metrics
#94
=> feat: Dashboard enhancements

backend/src/main/java/com/alibaba/higress/console/constant/CommonKey.java, backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/Route.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/route/HeaderControlConfig.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/route/ProxyNextUpstreamConfig.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java, backend/src/main/java/com/alibaba/higress/console/util/TypeUtil.java
1. Rewrite
2. Proxy next upstream
3. Request and response header control
fixes #59 #60 #62
=> feat: Implement some route features

frontend/src/pages/login/index.module.css, frontend/src/pages/login/index.tsx
Add language selector to the login page
fixes #87
=> feat: Add language selector to the login page

backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
=> feature: support route cors config

frontend/src/components/LanguageDropdown/index.tsx, frontend/src/components/Navbar/index.tsx
=> hotfix: Change language text display

.licenserc.yaml
Exclude *.yaml from license checker
=> fix: Exclude *.yaml from license checker.

backend/src/main/java/com/alibaba/higress/console/aop/ApiStandardizationAspect.java, backend/src/main/java/com/alibaba/higress/console/constant/CommonKey.java, backend/src/main/java/com/alibaba/higress/console/controller/ConfigController.java, frontend/src/app.ts, frontend/src/models/config.ts, frontend/src/pages/login/index.tsx, frontend/src/services/config.ts, frontend/src/services/request.tsx, frontend/src/store.ts, helm/templates/deployment.yaml, helm/values.yaml
Support adding a prompt to the login page
=> feat: Support adding a prompt to the login page

backend/src/main/java/com/alibaba/higress/console/constant/CommonKey.java, backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/Route.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/route/KeyedRoutePredicate.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
=> 路由管理功能支持Method、 Header、Query 等路由条件，实现路径匹配不区分大小写

backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/route/RoutePredicateTypeEnum.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java, frontend/.gitignore, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/route/components/FactorGroup/index.tsx
Fix malfunctions in route configuration with header, query and path case-insensitive predicates
=> fix: Fix malfunctions in route configuration with advance predicates

backend/src/main/resources/dashboard/main.json
Fix the pod name display in the CPU panel.
=> fix: Fix the pod name display in the CPU panel

helm/templates/grafana.yaml, helm/templates/prometheus.yaml, helm/values.yaml
Remove resource requests from grafana and prometheus deployments
=> fix: Remove resource requests from grafana and prometheus deployments

helm/Chart.yaml
release: Set version to 0.1.0.
=> release: Set version to 0.1.0.

backend/src/main/java/com/alibaba/higress/console/constant/CommonKey.java, backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java, backend/src/main/java/com/alibaba/higress/console/controller/WasmPluginInstancesController.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/WasmPluginInstance.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/WasmPluginInstanceScope.java, backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/WasmPluginInstanceService.java, backend/src/main/java/com/alibaba/higress/console/service/WasmPluginInstanceServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/wasm/ImagePullPolicy.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/wasm/MatchRule.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/wasm/PluginConfigAccessor.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/wasm/PluginConfigRuleAccessor.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/wasm/PluginPhase.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/wasm/V1alpha1WasmPlugin.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/wasm/V1alpha1WasmPluginList.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/wasm/V1alpha1WasmPluginSpec.java, backend/src/test/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverterTest.java
Support managing Wasm plugin instances, which allows user to bind Wasm plugins at global, domain and route levels.
=> feat: Support managing Wasm plugin instances

backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
Fix a possible NPE when operating service sources with an empty default V1McpBridge CR.
=> fix: Fix a possible NPE when operating service sources

backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSource.java, frontend/src/pages/service-source/components/SourceForm/index.tsx
Update validation of ServiceSource to allow an empty nacos namespace
=> fix: Update validation of ServiceSource to allow an empty nacos namespace

helm/templates/_helpers.tpl, helm/templates/deployment.yaml
1. Quote login prompt string.
2. Remove redundant "higress-" prefix in pod names.
=> fix: Fix some minor bugs in the helm chart

helm/templates/grafana.yaml, helm/templates/ingress.yaml, helm/templates/prometheus.yaml, helm/values.yaml
=> adjust ingress in helm

frontend/src/pages/route/index.tsx
fix: Fix the bug that route form shows the previous created route when opened for creating
=> fix: Fix the bug that route form shows the previous created route when opened for creating

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/login/index.tsx
fix: Fix the i18n issue of login button
=> fix: Fix the i18n issue of login button

backend/src/main/resources/plugins/basic-auth/spec.yaml
feat: Update the spec of basic-auth plugin with new scope field
=> feat: Update the spec of basic-auth plugin with new scope field

backend/src/main/java/com/alibaba/higress/console/controller/RoutesController.java
feat: Implement an API to query a single route by name
=> feat: Implement an API to query a single route by name

backend/src/main/resources/plugins/key-auth/README.md, backend/src/main/resources/plugins/key-auth/spec.yaml
为key_auth添加spec
[#135](https://github.com/higress-group/higress-console/issues/135)
=> feat: add key-auth plugin spec

backend/src/main/java/com/alibaba/higress/console/service/WasmPluginServiceImpl.java, backend/src/main/resources/plugins/key-auth/spec.yaml, backend/src/test/java/com/alibaba/higress/console/service/WasmPluginServiceTest.java
feat: Validate plugin spec files in UT
=> feat: Validate plugin spec files in UT

frontend/src/interfaces/service-source.ts, frontend/src/pages/service-source/index.tsx
Add a built-in K8s service source to the service source page
=> feat: Add a built-in K8s service source to the service source page

.github/workflows/deploy-to-k8s.yaml
Support deploying Higress Console to K8s via GitHub action
=> feat: Support deploying Higress Console to K8s via GitHub action

.github/workflows/deploy-to-k8s.yaml
feat: Support skipping the "Deploy to K8s" step in GitHub action
=> feat: Support skipping the "Deploy to K8s" step in GitHub action

backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
Fix bugs in CORS converting logic causing incorrect data saved to K8s
=> fix: Fix bugs in CORS converting logic causing incorrect data saved to K8s

frontend/src/pages/route/config/components/PluginDrawer/index.tsx, frontend/src/pages/route/config/components/PluginList/constant.ts, frontend/src/pages/route/config/components/PluginList/index.tsx, frontend/src/pages/route/config/components/Retries/index.tsx
=> fix: Update plug-in name get method

backend/src/main/java/com/alibaba/higress/console/constant/CommonKey.java, backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java, backend/src/main/java/com/alibaba/higress/console/controller/WasmPluginsController.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/Route.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSource.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/TlsCertificate.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/VersionedDto.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/WasmPlugin.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/WasmPluginInstance.java, backend/src/main/java/com/alibaba/higress/console/controller/util/ValidateUtil.java, backend/src/main/java/com/alibaba/higress/console/service/WasmPluginInstanceServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/WasmPluginService.java, backend/src/main/java/com/alibaba/higress/console/service/WasmPluginServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/wasm/MatchRule.java
Implement custom plugin support
=> feat: Implement custom plugin support

frontend/src/interfaces/route.ts, frontend/src/pages/route/config/components/PluginList/index.tsx, frontend/src/pages/route/config/components/Wasm/index.tsx, frontend/src/pages/route/config/index.tsx, frontend/src/services/plugin.ts
feat: add wasm plugin update/create/delete
=> feat: add wasm plugin update/create/delete

helm/templates/prometheus.yaml, helm/values.yaml
1. Support enabling local mode using global.local property.
2. Support switching to RWO mode for PVCs without enabling local mode.
fixes https://github.com/alibaba/higress/issues/267
=> feat: Improve local deployment support

backend/src/main/java/com/alibaba/higress/console/controller/WasmPluginCategory.java, backend/src/main/java/com/alibaba/higress/console/service/WasmPluginServiceImpl.java
feat: Coerce the category of user-created Wasm plugin to  "custom"
=> feat: Coerce the category of user-created Wasm plugin to  "custom"

backend/src/main/java/com/alibaba/higress/console/service/WasmPluginServiceImpl.java
Add a raw YAML example property into plugin config schema
=> feat: Add a raw YAML example property into plugin config schema

backend/src/main/resources/plugins/basic-auth/spec.yaml, backend/src/main/resources/plugins/hmac-auth/spec.yaml, backend/src/main/resources/plugins/jwt-auth/spec.yaml, backend/src/main/resources/plugins/key-auth/spec.yaml
1. Add global_auth property
2. Remove allow property from the example
=> feat: Update spec.yaml files of all the auth plugins

backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
Fill rawConfigurations field when building WasmPluginInstance
=> fix: Fill rawConfigurations field when building WasmPluginInstance

backend/src/main/java/com/alibaba/higress/console/controller/exception/ValidationException.java, backend/src/main/java/com/alibaba/higress/console/service/WasmPluginInstanceServiceImpl.java
feat: Return 400 when failed to parse raw YAML plugin configuration
=> feat: Return 400 when failed to parse raw YAML plugin configuration

frontend/src/pages/plugin/components/Wasm/index.tsx
=> fix: fix wasm plugin form tips

helm/templates/deployment.yaml, helm/values.yaml
1. Remove livenessProbe
2. Change imagePullPolicy from Always to IfNotPresent
=> fix: Normalize helm templates of Higress Console

frontend/src/components/CodeEditor/index.tsx, frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail.tsx, frontend/src/pages/plugin/components/PluginList/index.tsx, frontend/src/pages/plugin/components/Wasm/index.tsx, frontend/src/pages/plugin/index.tsx, frontend/src/services/plugin.ts, helm/templates/deployment.yaml, helm/values.yaml
=> fix: add route plugin get/update api

frontend/src/pages/plugin/components/PluginDrawer/RoutePluginDetail.tsx, frontend/src/pages/plugin/components/Rewrite/index.tsx
=> fix: Resolve routing plugin data rendering issues

backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSource.java
fix: Fix a typo in ServiceSource.validate method
=> fix: Fix a typo in ServiceSource.validate method

helm/templates/deployment.yaml, helm/templates/grafana.yaml, helm/templates/ingress.yaml, helm/templates/prometheus.yaml, helm/values.yaml
=> identify higress ingressClassName from global value

frontend/src/pages/plugin/components/Cors/index.tsx, frontend/src/pages/plugin/components/Retries/index.tsx
=> fix: add cors form defaultData

frontend/src/pages/domain/index.tsx, frontend/src/pages/plugin/components/PluginList/index.tsx, frontend/src/pages/plugin/components/Wasm/index.tsx, frontend/src/pages/route/index.tsx
Fix some bugs
1. Incorrect confirmation message displayed when trying to delete a route or domain
2. When adding or updating a custom Wasm plugin, imageRepository shouldn't contain the tag part
3. Fix the JS error occurred when plugin list shows two plugins with the same name
=> fix: Fix some bugs

backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java, backend/src/test/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverterTest.java
Fix the bug that unable to update route bound services
=> fix: Fix the bug that unable to update route bound services

backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
fix: Remove redundant .0 suffixes from WasmPlugin instance configurations
=> fix: Remove redundant .0 suffixes from WasmPlugin instance configurations

frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail.tsx
=> fix: plugin default value display issues

frontend/src/pages/route/index.tsx
=> fix: edit route detail coverage plugin config

backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
1. Remove leading YAML separator from raw configuration data
2. Sort objects listed by KubernetesClientService to ensure a stable order
=> fix: Add some minor tweaks

backend/src/main/java/com/alibaba/higress/console/controller/dto/WasmPlugin.java, backend/src/main/java/com/alibaba/higress/console/service/WasmPluginInstanceServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/WasmPluginServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java, backend/src/main/resources/plugins/plugins.properties
Use a separate field to store plugin version
=> feat: Use a separate field to store plugin version

frontend/src/pages/domain/config/index.tsx, frontend/src/pages/domain/index.tsx, frontend/src/pages/plugin/index.tsx, frontend/src/pages/route/config/index.tsx, frontend/src/pages/route/index.tsx
=> fix: Modifying plugin route  and headers text

backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java, frontend/src/pages/route/index.tsx
1. Fix the issue that ZK services cannot be displayed in the route list
2. Support displaying long service names with ellipse in the route list
=> fix: Fix route management malfunctions related to ZK services

helm/templates/grafana.yaml, helm/templates/prometheus.yaml, helm/values.yaml
Provide capability in Helm to specify storage class for Prometheus/Grafana.
N/A
No tests for Helm are available.
Use Helm template
=> feat: Provide capability in Helm to specify storage class for Prometheus/Grafana

frontend/ice.config.mts, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/404.tsx, frontend/src/pages/layout.tsx
Display a special error page when being nested in a frame of itself.
fixes #152
=> fix: Fix the issue of possible page nesting with iframe

frontend/src/components/Navbar/index.tsx, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json
=> add commercial info

backend/src/main/java/com/alibaba/higress/console/service/ServiceServiceImpl.java, frontend/src/pages/route/components/RouteForm/index.tsx
Fix the UI display issue caused duplicated service name and port combinations
=> fix: Fix the UI display issue caused duplicated service name and port combinations

helm/LICENSE, helm/README.md
Add LICENSE and README.md to the helm chart so we can have some details shown on artifacthub.io
=> feat: Add LICENSE and README.md to the helm chart

.github/workflows/deploy-to-k8s.yaml
Remove the actual deploy part from deploy-to-k8s action
=> fix: Remove the actual deploy part from deploy-to-k8s action

.github/workflows/deploy-to-k8s.yaml
Remove environment from deploy-to-k8s action
=> fix: Remove environment from deploy-to-k8s action

backend/src/main/java/com/alibaba/higress/console/controller/DomainsController.java, backend/src/main/java/com/alibaba/higress/console/controller/ServiceSourceController.java, backend/src/main/java/com/alibaba/higress/console/controller/TlsCertificatesController.java, backend/src/main/java/com/alibaba/higress/console/controller/WasmPluginsController.java
Fix the incorrect 200 response returned by a failed delete operation
=> fix: Fix the incorrect 200 response returned by a failed delete operation

.github/workflows/deploy-to-k8s.yaml
fix: Fix the incorrect image name used by GitHub Action
=> fix: Fix the incorrect image name used by GitHub Action

backend/src/main/resources/dashboard/main.json
=> update memory stats

helm/templates/NOTES.txt, helm/templates/_helpers.tpl, helm/templates/certmanager.yaml, helm/templates/configmap.yaml, helm/templates/deployment.yaml, helm/templates/grafana.yaml, helm/templates/ingress.yaml, helm/templates/prometheus.yaml, helm/templates/secret.yaml, helm/templates/service.yaml, helm/values.yaml
1. Add HIGRESS_CONSOLE_NS environment variable to the console container to avoid authentication error when installed to a namespace other than "higress-system"
2. Not to change resource names by the release name
3. Fix incorrect namespace values in certmanager.yaml
=> fix: Fix some bugs in the helm chart

backend/src/main/java/com/alibaba/higress/console/constant/CommonKey.java, backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java, helm/templates/_helpers.tpl, helm/templates/deployment.yaml
=> feat: Support accessing controller debug APIs when controller uses first-party-jwt policy

helm/templates/grafana.yaml, helm/templates/prometheus.yaml
Fix possible nil pointer errors thrown when installing with o11y enabled
=> fix: Fix possible nil pointer errors thrown when installing with o11y enabled

backend/src/main/resources/dashboard/main.json
fix upstream success rate expression.
=> fix upstream sucess rate

backend/src/main/java/com/alibaba/higress/console/constant/UserConfigKey.java, backend/src/main/java/com/alibaba/higress/console/controller/ConfigController.java, backend/src/main/java/com/alibaba/higress/console/service/ConfigService.java, backend/src/main/java/com/alibaba/higress/console/service/ConfigServiceImpl.java, helm/Chart.yaml, helm/templates/configmap.yaml, helm/templates/deployment.yaml, helm/values.yaml
Unify all the user-configurations into the ConfigMap and support AI chat configurations.
=> feat: Support configuring the AI chat component in the backend

helm/templates/prometheus.yaml, helm/values.yaml
Disable Prometheus Ingress by default. User can enable it via Helm parameter if needed.
=> fix: Disable Prometheus Ingress by default

backend/src/main/java/com/alibaba/higress/console/aop/ApiStandardizationAspect.java, backend/src/main/java/com/alibaba/higress/console/constant/CommonKey.java, backend/src/main/java/com/alibaba/higress/console/constant/UserConfigKey.java, backend/src/main/java/com/alibaba/higress/console/controller/SystemController.java, backend/src/main/java/com/alibaba/higress/console/controller/UserController.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/ChangePasswordRequest.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/SystemInitRequest.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/User.java, backend/src/main/java/com/alibaba/higress/console/controller/util/ControllerUtil.java, backend/src/main/java/com/alibaba/higress/console/service/ConfigService.java, backend/src/main/java/com/alibaba/higress/console/service/ConfigServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/SessionService.java, backend/src/main/java/com/alibaba/higress/console/service/SessionServiceImpl.java, frontend/ice.config.mts, frontend/src/app.ts, frontend/src/services/config.ts, frontend/src/services/system.ts, frontend/src/services/user.ts
Update configuration APIs according to the new design
1. Add /system/init
2. Add /user/changePassword
3. Move /session/check to /user/info
4. Move /config to /system/config
=> feat: Update configuration APIs according to the new design

frontend/src/interfaces/config.ts, frontend/src/pages/login/index.tsx, frontend/src/pages/plugin/components/Wasm/index.tsx, frontend/src/pages/plugin/index.tsx, frontend/src/pages/service-source/index.tsx
Support hiding Kubernetes service source when running in standalone mode.
=> feat: Support hiding Kubernetes service source when running in standalone mode

.github/workflows/deploy-to-oss.yaml
=> add cn-index.yaml

frontend/package-lock.json, frontend/package.json, frontend/yarn.lock
=> Feat: add robot loading and change error text

frontend/package-lock.json, frontend/package.json, frontend/yarn.lock
=> fix: gpt-robot scrollBottom

backend/src/main/resources/plugins/plugins.properties, backend/src/main/resources/plugins/waf/README.md, backend/src/main/resources/plugins/waf/spec.yaml
Upgrade built-in WAF plugin to 1.0.1.
=> feat: Upgrade built-in WAF plugin to 1.0.1

frontend/src/components/Navbar/index.tsx, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json
Fix incorrect item names and links pointed to the old website used in the top navbar.
=> fix: Update texts and links used in the top navbar

frontend/src/interfaces/service-source.ts
=> fix: Fix a spelling error in service source type "Consul".

.github/workflows/deploy-to-k8s.yaml
Support arm64 platform in Higress Console image.
https://hub.docker.com/layers/ch3cho/higress-console/sha-11de56e/images/sha256-07fa4222fbf7e28fe1f81d8ec53802c03c9ca2539563bac3e91a47e9940bc8b9?context=repo
=> feat: Support arm64 platform in Higress Console image

frontend/src/pages/tls-certificate/index.tsx
Send version when updating a TLS certificate to avoid concurrent operation.
=> fix: Send version when updating a TLS certificate to avoid concurrent operation

backend/src/main/resources/plugins/request-block/spec.yaml
update spec.yaml for request block plugin
=> feat: update spec.yaml for request block plugin

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/dashboard/index.tsx
Update the dashboard page displayed in standalone deployment. Key differences are as following:
=> feat: Update the dashboard page displayed in standalone deployment

backend/src/main/java/com/alibaba/higress/console/aop/ApiStandardizationAspect.java, backend/src/main/java/com/alibaba/higress/console/controller/HealthzController.java
Add a dummy /healthz/ready endpoint for a light-weight health check for Docker Compose to check the startup status of the console service.
=> feat: Add a dummy /healthz/ready endpoint for a light-weight health check

backend/src/main/java/com/alibaba/higress/console/controller/ServiceSourceController.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSource.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSourceAuthN.java, backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceService.java, backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/mcp/V1McpBridge.java, backend/src/main/java/com/alibaba/higress/console/service/kubernetes/crd/mcp/V1RegistryConfig.java, backend/src/test/java/com/alibaba/higress/console/service/WasmPluginServiceTest.java, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/service-source/components/SourceForm/index.tsx
1. Support new registry types "consul" and "eureka" on the backend
2. Implement API support of configuring registry authentication info
3. Support configuring authentication info of Nacos registries on the frontend
fixes #246
=> feat: Enhance service source management function

frontend/src/interfaces/service-source.ts, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/service-source/components/SourceForm/index.tsx
Support configuring consul and eureka service sources.
=> feat: Support configuring consul and eureka service sources

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json
Fix the incorrect path of the metrics endpoint
=> fix: Fix the incorrect path of the metrics endpoint

frontend/src/pages/route/components/RouteForm/index.tsx
remove domain field required when create/update route
fixes #256
=> fix: remove domain field required when create/update route (#513)

backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java
Propagate service list loading errors to the frontend.
=> fix: Propagate service list loading errors to the frontend

backend/Dockerfile
Add curl into the image to support sending healthcheck requests in the container, so healthcheck configurations in docker-compose of standalone deployment can run correctly.
=> feat: Add curl into the image to support sending healthcheck requests

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json
Add descriptions of selecting an empty domain in route.
=> fix: Add descriptions of selecting an empty domain in route

backend/src/main/resources/dashboard/main.json
=> fix: Fix the malfunction "Upstream Success Rate" chart in the built-in dashboard

.github/workflows/deploy-to-k8s.yaml, backend/.gitignore, backend/build.sh, backend/pom.xml, backend/src/main/java/com/alibaba/higress/console/constant/CommonKey.java, backend/src/main/java/com/alibaba/higress/console/controller/SystemController.java, backend/src/main/java/com/alibaba/higress/console/controller/dto/SystemInfo.java, backend/src/main/java/com/alibaba/higress/console/service/DashboardServiceImpl.java, backend/src/main/java/com/alibaba/higress/console/service/SystemService.java, backend/src/main/java/com/alibaba/higress/console/service/SystemServiceImpl.java, backend/src/main/resources/application.properties, backend/style/higress_suppressions.xml, frontend/src/app.ts, frontend/src/components/Footer/index.tsx, frontend/src/models/system.ts, frontend/src/services/system.ts, frontend/src/store.ts
1. Use maven property placeholder and build variables write the actual build version into the configuration file.
2. Expose the version info through API endpoint /system/info.
3. Update footer content to show additional version info if available.
**Official release built through a "v*.*.*" tag:**
**Snapshot release built from a branch (not from a tag):**
fixes #263
=> feat: Show build version in footer

frontend/src/pages/route/components/RouteForm/index.tsx
Add pattern validation to route name.
=> fix: Add pattern validation to route name

backend/src/main/java/com/alibaba/higress/console/constant/UserConfigKey.java, backend/src/main/java/com/alibaba/higress/console/service/SessionServiceImpl.java
Support disabling password change function, so we have it disabled on our demo console.
=> feat: Support disabling password change function

frontend/src/pages/dashboard/index.tsx
=> fix: Fix some typos in dashboard page

helm/values.yaml
Remove Ingress related configurations.
=> fix: Remove Ingress related configurations

backend/console/src/main/java/com/alibaba/higress/console/constant/CapabilityKey.java, backend/console/src/main/java/com/alibaba/higress/console/controller/dto/SystemInfo.java, backend/console/src/main/java/com/alibaba/higress/console/service/SystemServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesClientService.java, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/route/index.tsx
Disable route management for K8s < 1.19.
=> feat: Disable route management for K8s < 1.19

frontend/src/pages/route/index.tsx
Fix the missing action links issue in the route list.
=> fix: Fix the missing action links issue in the route list

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java
Not to consider disabled annotations as custom annotations, so they won't be shown on the custom annotation area.
=> fix: Not to consider disabled annotations as custom annotations

backend/sdk/src/main/java/com/alibaba/higress/sdk/constant/KubernetesConstants.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java
Support editing pseudo-header match rules in routes.
=> feat: Support editing pseudo-header match rules in routes

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/route/components/RouteForm/index.tsx, frontend/src/pages/route/index.tsx
console简单支持配置多个目标服务，以默认权重。暂未支持自定义权重。
fixes https://github.com/alibaba/higress/issues/837
=> feat: console supports configuration of multiple target services

.github/workflows/build-and-test.yaml
Run unit tests in GitHub actions.
=> fix: Run unit tests in GitHub actions

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesClientService.java
Fix the auth error returned by controller due to token expiration, which causes empty service list shown on the webpage.
=> fix: Fix the auth error returned by controller due to token expiration

backend/console/pom.xml, backend/pom.xml, backend/sdk/pom.xml, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/WasmPluginConfig.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/wasmplugin/PluginConfigSchema.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/wasmplugin/PluginInfo.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/WasmPluginInstanceServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/WasmPluginServiceImpl.java
=> Replace openapi parsing framework

frontend/src/document.tsx
Remove the default page description.
=> fix: Remove the default page description

backend/sdk/src/main/resources/plugins/ai-proxy/README.md, backend/sdk/src/main/resources/plugins/ai-proxy/spec.yaml, backend/sdk/src/main/resources/plugins/plugins.properties
=> feat: Add AI proxy plugin

backend/sdk/src/main/resources/plugins/ai-cache/spec.yaml, backend/sdk/src/main/resources/plugins/plugins.properties
=> feat: Add ai-cache Wasm plugin

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/WasmPluginServiceImpl.java, frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail.tsx
=> fix: Fix the bug that plugin configuration example is shown empty

helm/templates/NOTES.txt, helm/templates/ingress.yaml, helm/values.yaml
Allow user to create an ingress for console. But the ingress won't be created by default.
=> feat: Allow user to create an ingress for console

frontend/src/pages/service-source/components/SourceForm/index.tsx
Fix the malfunctioning port field in the service source form.
Reference: https://4x.ant.design/components/form/#components-form-demo-complex-form-control
=> fix: Fix the malfunctioning port field in the service source form

backend/sdk/src/main/resources/plugins/ai-proxy/spec.yaml
This affects the sample configuration shown on the console page.
=> fix: Fix the property type of apiTokens used in ai-proxy plugin

helm/values.yaml
Load 3rd-party images from higress image repo.
=> feat: Load 3rd-party images from higress image repo

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail.tsx, frontend/src/pages/route/index.tsx
1. Only ingresses configured via console is listed in route config page.
2. Please edit plugins' global configuration with caution.
=> feat: Add some notes

helm/Chart.yaml, helm/templates/deployment.yaml, helm/values.yaml
Support disabling swagger APIs via a helm chart property.
=> feat: Support disabling swagger APIs via a helm chart property

backend/pom.xml
1. Upgrade Spring Boot to the latest version of 2.x series
2. Support developing with Java 21.
fixes #305
=> feat: Upgrade Spring Boot and support Java 21

README.md, backend/sdk/src/main/resources/plugins/ai-agent/spec.yaml, backend/sdk/src/main/resources/plugins/ai-history/spec.yaml, backend/sdk/src/main/resources/plugins/ai-intent/spec.yaml, backend/sdk/src/main/resources/plugins/ai-quota/spec.yaml, backend/sdk/src/main/resources/plugins/ext-auth/spec.yaml, backend/sdk/src/main/resources/plugins/frontend-gray/spec.yaml, backend/sdk/src/main/resources/plugins/geo-ip/spec.yaml, backend/sdk/src/main/resources/plugins/oidc/spec.yaml, backend/sdk/src/main/resources/plugins/plugins.properties, backend/sdk/src/main/resources/plugins/transformer/spec.yaml
=> feat: add new plugin

backend/sdk/src/main/resources/plugins/plugins.properties
=> feat: Use latest as the image tag for all plugins

backend/sdk/src/main/resources/plugins/ai-security-guard/spec.yaml
默认展示是否启用的参数
AI 内容安全插件展示的默认参数里面没有带是否启用的参数
造成不了解完整参数的用户在启用该插件后会有插件没有生效的错误感知。
easy to understand
just a example which show to the user, no need to verify anything
=> 优化 AI 内容安全插件参数示例

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/plugin/components/HeaderModify/index.tsx
1. Remove the required constraint when adding a header delete action.
2. Ignore header actions with an empty key.
=> fix: Fix some bugs in header control configurations

backend/sdk/src/main/resources/plugins/basic-auth/spec.yaml, backend/sdk/src/main/resources/plugins/key-auth/spec.yaml
Update the "scope" field names used in Wasm spec.yaml files according to the updated document: https://github.com/higress-group/higress-group.github.io/pull/325
=> fix: Update the "scope" field names used in Wasm spec.yaml files

backend/style/higress_formatter.xml
Fix a typo  in higress_formatter.xml
No
Don't need
=> fix: Fix a typo in higress_formatter.xml

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/WasmPluginServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesUtil.java, backend/sdk/src/main/resources/plugins/basic-auth/spec.yaml, frontend/src/pages/layout.tsx
1. Fix the K8s API error occurred when loading domain list.
2. Remove unnecessary trailing spaces in basic-auth/spec.yaml.
3. Fix the incorrect Wasm plugin config example with routeConfigSchema in spec.yaml.
4. Incorrect layout used in init and login pages.
=> fix: Fix several bugs

backend/sdk/src/main/java/com/alibaba/higress/sdk/constant/BuiltInPluginName.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/constant/CommonKey.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/constant/HigressConstants.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ai/AiModelPredicate.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ai/AiRoute.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/HigressServiceProviderImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AbstractLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AiRouteServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/LlmProviderServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/consumer/ConsumerServiceImpl.java, backend/sdk/src/main/resources/plugins/model-router/README.md, backend/sdk/src/main/resources/plugins/model-router/README_EN.md, backend/sdk/src/main/resources/plugins/model-router/spec.yaml, backend/sdk/src/main/resources/plugins/plugins.properties
1. Support Moonshot LLM provider.
2. Support model router.
=> feat: Add more functions to AI console APIs

frontend/src/pages/_defaultProps.tsx
Hide AI related menu items since they haven't been finished yet and release can be performed without showing them to all users.
=> fix: Hide AI related menu items

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AiRouteServiceImpl.java, helm/templates/clusterrole.yaml
1. Grant permission to operate EnvoyFilters in helm chart.
2. Generate fallback resources in AiRouteServiceImpl.add as well.
3. Fill some default values shown as null previously.
=> fix: Fix some bugs in AI console APIs

backend/sdk/src/main/resources/plugins/request-block/README.md, backend/sdk/src/main/resources/plugins/request-block/README_EN.md
=> update request block doc

helm/templates/deployment.yaml
…nt readnessProbe.
- modify helm template containerPort to avoid svc ports impact deployment readnessProbe.
fixes #381
=> modify helm template containerPort to avoid svc ports impact deployment readnessProbe.

backend/console/src/main/resources/application.properties, helm/Chart.yaml, helm/templates/deployment.yaml
Fix the swagger switch in the helm chart which stops working after we switch to SpringDoc from SpringFox.
=> fix: Fix the swagger switch in the helm chart

frontend/src/pages/_defaultProps.tsx
Reverts higress-group/higress-console#364
=> Revert "fix: Hide AI related menu items"

backend/sdk/src/main/resources/plugins/ai-cache/spec.yaml
=> fix default config of ai-cache plugin

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/route/index.tsx
Add a new domain column to the route list.
fixes #358
=> feat: Add a new domain column to the route list

backend/console/src/main/java/com/alibaba/higress/console/controller/SystemController.java
Fix a possible dead-loop during initialization caused by an inconsistent internal config state, initialization not set but admin user configured.
=> fix: Fix a possible dead-loop during initialization

backend/sdk/src/main/java/com/alibaba/higress/sdk/constant/plugin/config/AiProxyConfig.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/constant/plugin/config/KeyAuthConfig.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AbstractLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/consumer/KeyAuthCredentialHandler.java, frontend/package-lock.json, frontend/package.json, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/ai/components/ProviderForm/index.tsx, frontend/src/pages/ai/components/RouteForm/index.tsx, frontend/src/pages/ai/route.tsx
1. Add usage info.
2. Fix key-auth.global_auth flag.
3. Fix model mapping function.
4. Enable retryOnFailure if failover is enabled in a provider.
5. Fix the display issue of the provider's failover switch
=> fix: Fix some issues in AI console

backend/console/src/main/resources/dashboard/ai.json
=> update ai dashboard

backend/sdk/src/main/resources/plugins/plugins.properties
Update the version of all built-in plugins to 1.0.0.
=> feat: Update the version of all built-in plugins to 1.0.0

frontend/src/pages/layout.tsx, frontend/src/pages/plugin/components/PluginList/index.tsx
Hide some built-in plugins for AI Route.
=> fix: Hide some built-in plugins for AI Route

backend/console/src/main/java/com/alibaba/higress/console/aop/ApiStandardizationAspect.java
Not to log AuthExceptions because it's a normal business scenario.
=> fix: Not to log AuthExceptions

frontend/src/pages/route/index.tsx, frontend/src/switches.ts
Hide AI routes in the route list。
=> fix: Hide AI routes in the route list

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ServiceServiceImpl.java, frontend/src/pages/service-source/index.tsx
fixes https://github.com/alibaba/higress/issues/1682
=> feat: Show port info of MCP services

backend/console/pom.xml, backend/console/src/test/java/com/alibaba/higress/console/FrontEndI18nResourceChecker.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ai/LlmProviderType.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AbstractLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AzureLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/OllamaLlmProviderHandler.java, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/ai/components/ProviderForm/index.tsx, frontend/src/pages/ai/configs.tsx, frontend/src/pages/ai/provider.tsx, frontend/src/pages/route/components/RouteForm/index.tsx
Support more LLM providers on the frontend.
=> feat: Support more LLM providers on the frontend

frontend/src/interfaces/config.ts, frontend/src/pages/index.tsx
Support customizing the redirection target of the index page.
=> feat: Support customizing the redirection target of the index page

backend/sdk/src/main/java/com/alibaba/higress/sdk/constant/HigressConstants.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ai/AiRoute.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/route/RoutePredicate.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AiRouteServiceImpl.java, frontend/src/interfaces/ai-route.ts, frontend/src/interfaces/llm-provider.ts, frontend/src/pages/ai/components/RouteForm/index.tsx, frontend/src/pages/ai/provider.tsx, frontend/src/pages/ai/route.tsx
Support customizing path, header and URL param predicates in AI Route.
=> feat: Support customizing path, header and URL param predicates in AI Route

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/LlmProviderServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/OpenaiLlmProviderHandler.java, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/ai/components/ProviderForm/index.tsx, frontend/src/pages/ai/configs.tsx
Support configuring custom service URL in OpenAI type of LLM providers
fixes https://github.com/alibaba/higress/issues/1712
=> feat: Support configuring custom service URL in OpenAI type of LLM providers

backend/console/src/main/java/com/alibaba/higress/console/service/SessionServiceImpl.java
Support authentication with HTTP basic auth in API calls.
=> feat: Support HTTP basic auth in API calls

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/dashboard/index.tsx, frontend/src/services/dashboard.ts
=> feat: Support downloading AI dashboard configurations

backend/sdk/src/main/java/com/alibaba/higress/sdk/constant/HigressConstants.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/constant/KubernetesConstants.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesClientService.java
Add a comment annotation to internal resources to let user know the resource shouldn't be edited directly.
=> feat: Add a comment annotation to internal resources

helm/templates/deployment.yaml, helm/values.yaml
Support changing the controller service name in Helm chart.
=> feat: Support changing the controller service name in Helm chart

frontend/src/pages/dashboard/index.tsx
Update Prometheus relabel_configs provided on the dashboard page.
=> feat: Update Prometheus relabel_configs provided on the dashboard page

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/service/index.tsx
1. Add "FQDN" to the title of service name column.
2. Move service port to a separate column.
=> feat: Improve the service list page

backend/sdk/src/main/java/com/alibaba/higress/sdk/model/PaginatedResult.java
修改分页类中
public static <T, V> PaginatedResult<V> createFromFullList(List<T> list, CommonPageQuery query, Function<T, V> converter)
函数取值错误的问题
=> 修复 issue #434: 分页类中，分页取值取错的问题

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/ai/components/ProviderForm/index.tsx
1. Update the label and sample of OpenAI custom URL field.
2. Move the token failback switch to its correct position.
=> fix: Fix some display issues on the AI route edit page

backend/console/src/main/java/com/alibaba/higress/console/service/SystemServiceImpl.java
Use EQUAL match instead of PREFIX match in the generated default route.
=> fix: Use EQUAL match in the generated default route

backend/console/src/main/java/com/alibaba/higress/console/controller/AiProxyController.java
Remove some unnecessary error logs from AiProxyController.
=> fix: Remove some unnecessary error logs from AiProxyController

backend/sdk/src/main/resources/plugins/ai-search/README.md, backend/sdk/src/main/resources/plugins/ai-search/README_EN.md, backend/sdk/src/main/resources/plugins/ai-search/spec.yaml, backend/sdk/src/main/resources/plugins/plugins.properties
=> add ai-search plugin info

backend/console/src/main/resources/dashboard/ai.json
新增首个 token 延时和请求消耗时长的图表。
Related PR: https://github.com/alibaba/higress/pull/1889/files
=> feat: add first token latency and request process duration panel

helm/templates/deployment.yaml, helm/values.yaml
Implement custom environment variables to meet enterprise-specific configuration needs for on-premises deployment scenarios.
=> feat: Support for customizing environment variables

frontend/src/interfaces/ai-route.ts, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/ai/route.tsx, frontend/src/pages/route/index.tsx, frontend/src/pages/service/index.tsx
=> feat: Add filter function to the AI route list

backend/console/src/main/java/com/alibaba/higress/console/controller/ConsumersController.java, backend/console/src/main/java/com/alibaba/higress/console/controller/DomainsController.java, backend/console/src/main/java/com/alibaba/higress/console/controller/ServiceSourceController.java, backend/console/src/main/java/com/alibaba/higress/console/controller/ServicesController.java, backend/console/src/main/java/com/alibaba/higress/console/controller/TlsCertificatesController.java, backend/console/src/main/java/com/alibaba/higress/console/controller/WasmPluginsController.java, backend/console/src/main/java/com/alibaba/higress/console/controller/ai/AiRoutesController.java, backend/console/src/main/java/com/alibaba/higress/console/controller/ai/LlmProvidersController.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/CommonPageQuery.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/PaginatedResult.java
Fix incorrect query parameter displays in the swagger doc.
fixes #458
=> fix: Fix incorrect query parameter displays in the swagger doc

backend/sdk/src/main/resources/plugins/ai-search/spec.yaml, backend/sdk/src/main/resources/plugins/frontend-gray/spec.yaml, backend/sdk/src/main/resources/plugins/mcp-server/README.md, backend/sdk/src/main/resources/plugins/mcp-server/README_EN.md, backend/sdk/src/main/resources/plugins/mcp-server/spec.yaml, backend/sdk/src/main/resources/plugins/plugins.properties
=> add mcp server plugin

backend/sdk/src/main/resources/plugins/mcp-server/README.md, backend/sdk/src/main/resources/plugins/mcp-server/README_EN.md, backend/sdk/src/main/resources/plugins/mcp-server/spec.yaml
=> update mcp-server README

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ServiceSourceServiceImpl.java
Fix an NPE when deleting a nonexistent registry.
=> fix: Fix an NPE when deleting a nonexistent registry

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/plugin/components/PluginCategory/index.module.css, frontend/src/pages/plugin/components/PluginCategory/index.tsx, frontend/src/pages/plugin/components/PluginList/constant.ts, frontend/src/pages/plugin/components/PluginList/index.tsx
增加插件分类栏
https://github.com/user-attachments/assets/48609314-162d-4e5f-967f-3edbe9530319
fixes https://github.com/higress-group/higress-console/issues/459
=> feat: categorize plugins

backend/sdk/src/main/resources/plugins/plugins.properties
=> feat: Add ai-data-masking plugin into the list

frontend/src/pages/service-source/components/SourceForm/index.tsx
Reproducing steps:
1. Click "Create Service Source" button.
2. Set type to "DNS".
3. Set protocol to "HTTPS" to show the SNI input.
4. Close the create form.
5. Click "Create Service Source" button again.
=> fix: Fix an display issue of SNI input in the service source form

backend/console/src/main/resources/application.properties, backend/sdk/pom.xml
1. Disable swagger by default.
2. Remove a redundant Bouncy Castle dependency.
=> fix: Disable swagger by default and remove a redundant Bouncy Castle dependency

backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ServiceSource.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ServiceSourceAuthN.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/crd/mcp/V1McpBridge.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/crd/mcp/V1RegistryConfig.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/util/ValidateUtil.java, frontend/src/interfaces/service-source.ts, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/service-source/components/SourceForm/index.tsx
Support a new registry type: nacos3.
=> feat: Support a new registry type: nacos3

frontend/src/pages/service-source/components/SourceForm/index.tsx
=> fix: Fix an incorrect text

frontend/src/pages/ai/components/RouteForm/index.tsx, frontend/src/pages/ai/route.tsx
Fix the bug of unable to enable ignore path case matching for AI routes.
fixes https://github.com/higress-group/higress-console/issues/507
=> fix: Fix the bug of unable to enable ignore path case matching for AI routes

backend/console/src/main/java/com/alibaba/higress/console/controller/SystemController.java, backend/console/src/main/java/com/alibaba/higress/console/service/SystemServiceImpl.java, frontend/src/pages/system/index.tsx, frontend/src/services/system.ts
1. Using PUT instead of POST when calling /system/higress-config API since it's an update operation other than create.
2. Display a message when higress-config is updated successfully.
3. Fix a typo in a method name.
=> fix: Fix some bugs in higress-config updating function

frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json
Update display name of OpenAI provider type.
=> fix: Update display name of OpenAI provider type

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesClientService.java
Currently, if we fail to determine whether Ingress v1 resource is supported or not, we treat it as not supported. However, if any timeout or error occurs in this single time check request, the console won't work as expected. So this PR improves the K8s capabilities init logic.
1. Add retry to the init request.
2. If all fail, treat as Ingress V1 supported.
=> feat: Improve the K8s capabilities init logic

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/crd/mcp/V1RegistryConfig.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/crd/mcp/V1RegistryConfigMetadata.java
Update McpBridge according to the new CRD in Higress 2.1.4.
=> feat: Update McpBridge according to the new CRD in Higress 2.1.4

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/crd/mcp/V1RegistryConfigMetadata.java
=> fix: Add a missing annotation

helm/templates/deployment.yaml, helm/values.yaml
fix: "UrlPattern" to "urlPattern"
=> fix: "UrlPattern" to "urlPattern"

backend/sdk/src/main/resources/plugins/plugins.properties
=> feat: upgrade the plugins version from 1.0.0 to 2.0.0

backend/sdk/src/main/java/com/alibaba/higress/sdk/service/mcp/detail/DatabaseDetailStrategy.java
Add DB MCP Server execute, list tables, describe table tools schema Config. 
To view the DB MCP Server tools configuration in the console and keep it consistent with the configuration in higress-gateway. related PR：https://github.com/alibaba/higress/pull/2506
related: https://github.com/alibaba/higress/issues/2247
=> feat: add DB MCP Server execute, list tables, describe table tools schema Config

frontend/src/pages/ai/components/ProviderForm/index.tsx
Fix a typo causing "Cannot read properties of undefined" error when editing an OpenAI type of LLM provider.
fixes #567
=> fix: Fix a typo causing "Cannot read properties of undefined" error

backend/console/src/main/java/com/alibaba/higress/console/config/SdkConfig.java, backend/console/src/main/java/com/alibaba/higress/console/controller/ProxyServerController.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ProxyServer.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ServiceSource.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/model/ai/LlmProvider.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/HigressServiceProvider.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/HigressServiceProviderImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ProxyServerService.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ProxyServerServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/AbstractLlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/LlmProviderHandler.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/ai/LlmProviderServiceImpl.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverter.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/crd/mcp/V1McpBridge.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/crd/mcp/V1McpBridgeSpec.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/crd/mcp/V1ProxyConfig.java, backend/sdk/src/main/java/com/alibaba/higress/sdk/service/kubernetes/crd/mcp/V1RegistryConfig.java, backend/sdk/src/test/java/com/alibaba/higress/sdk/service/kubernetes/KubernetesModelConverterTest.java, frontend/src/interfaces/llm-provider.ts, frontend/src/interfaces/proxy-server.ts, frontend/src/locales/en-US/translation.json, frontend/src/locales/zh-CN/translation.json, frontend/src/pages/ai/components/ProviderForm/index.tsx, frontend/src/pages/ai/provider.tsx, frontend/src/pages/service-source/components/SourceForm/index.tsx, frontend/src/pages/service-source/index.tsx, frontend/src/services/proxy-server.ts
Support managing proxy servers based on https://github.com/alibaba/higress/pull/2710
=> feat: Support managing proxy servers

frontend/src/pages/plugin/components/Rewrite/index.tsx
Allow clearing and disabling route rewrite config to fix the error below;
=> fix: Allow clearing and disabling route rewrite config
